# Generated by Django 2.2 on 2021-09-15 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_noteshare_shared_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteshare',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='share', to='note.NOTE'),
        ),
    ]
