# Generated by Django 2.2 on 2021-09-15 15:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0004_auto_20210915_1113'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='noteshare',
            unique_together={('note', 'shared_with')},
        ),
    ]
